# Assignment 4
# IE 5137 Computational Modelling in Industrial Engineering

### Question 1

For the two-dimensional array

<pre><code><strong>
a = np.array([[4.0, 7.0, -2.43, 67.1],
              [-4.0, 64.0, 54.7, -3.33],
              [2.43, 23.2, 3.64, 4.11],
              [1.2, 2.5, -113.2, 323.2]])
</pre></code></strong>
use array slicing to perform the following operations, printing the results to the screen:\
&nbsp;&nbsp;&nbsp;&nbsp;(a) Extract the square root of the third column as a 1D array\
&nbsp;&nbsp;&nbsp;&nbsp;(b) Extract the bottom right quadrant as a 2D sub-array\
&nbsp;&nbsp;&nbsp;&nbsp;(c) Extract all rows with an even index as a 2D sub-array\
&nbsp;&nbsp;&nbsp;&nbsp;(d) Extract all elements on the diagonal as a Python list\
Try to use slicing such that your code would still work if the dimensions of a were enlarged.


In [13]:
import numpy as np
a = np.array([[4.0,7.0,-2.43,67.1,1,1],
              [-4.0,64.0,54.7,-3.33,1,1],
              [2.43,23.2,3.64,4.11,1,1],
              [1.2,2.5,-113.2,323.2,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1]])

In [14]:
a

array([[   4.  ,    7.  ,   -2.43,   67.1 ,    1.  ,    1.  ],
       [  -4.  ,   64.  ,   54.7 ,   -3.33,    1.  ,    1.  ],
       [   2.43,   23.2 ,    3.64,    4.11,    1.  ,    1.  ],
       [   1.2 ,    2.5 , -113.2 ,  323.2 ,    1.  ,    1.  ],
       [   1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ],
       [   1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ]])

In [6]:
a[2]**(1/2)

array([1.55884573, 4.81663783, 1.9078784 , 2.02731349])

In [15]:
i = int(a.shape[0]/2)
j = int(a.shape[1]/2)

a[i:,j:]

array([[323.2,   1. ,   1. ],
       [  1. ,   1. ,   1. ],
       [  1. ,   1. ,   1. ]])

In [18]:
i = int(a.shape[0])

a[0:i:2,::]

array([[ 4.  ,  7.  , -2.43, 67.1 ,  1.  ,  1.  ],
       [ 2.43, 23.2 ,  3.64,  4.11,  1.  ,  1.  ],
       [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ]])

In [58]:
b=[]
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if i == j:
            b.append(a[i][j])

### Question 2

Create the following 5x5 array without typing it explicitly:
<pre><code><strong>
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
</pre></code></strong>

_(Hint: The transpose function might come in handy.)_

Then divide each column element-wise by the one-dimensional array:\
`b = np.array([1, 5, 10, 15, 20])`


In [19]:
c = np.array(range(1,26)).reshape(5,5).transpose()
c

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [24]:
b = np.array([1,5,10,15,20]).reshape(5,1)
b

array([[ 1],
       [ 5],
       [10],
       [15],
       [20]])

In [25]:
c/b

array([[ 1.        ,  6.        , 11.        , 16.        , 21.        ],
       [ 0.4       ,  1.4       ,  2.4       ,  3.4       ,  4.4       ],
       [ 0.3       ,  0.8       ,  1.3       ,  1.8       ,  2.3       ],
       [ 0.26666667,  0.6       ,  0.93333333,  1.26666667,  1.6       ],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

### Question 3

Generate a 10x5 array of random numbers distributed uniformly between 0 and 1.\
For each row, extract the number closest to 0.5.

_(Hint: Use the abs and argmin functions to find the desired element for each row, then use fancy indexing (`a[i,j]` where both i and j are arrays) to pick those values out.)_


In [27]:
import random as r

d = np.random.rand(10,5)
print(d)

z = abs(d-0.5)
#print(z)

j = np.argmin(z,axis=1)
i = np.arange(10)

print(d[i,j])

[[0.19954328 0.4100295  0.59649994 0.91779434 0.70788695]
 [0.92334279 0.07826593 0.73269498 0.27890587 0.39931929]
 [0.95240765 0.72747743 0.57719203 0.08685144 0.84857157]
 [0.89782067 0.75340495 0.48919957 0.46873526 0.74896767]
 [0.17074025 0.05844532 0.29847524 0.7515238  0.77795881]
 [0.79900313 0.15909031 0.57472615 0.85897591 0.27971287]
 [0.96048089 0.622454   0.79063193 0.64071651 0.66540855]
 [0.34184442 0.67120305 0.98173705 0.70458723 0.17766662]
 [0.59111992 0.5450612  0.45872605 0.05887425 0.29209596]
 [0.22302992 0.53188436 0.00127691 0.78637313 0.10089774]]
[0.4100295  0.39931929 0.57719203 0.48919957 0.29847524 0.57472615
 0.622454   0.34184442 0.45872605 0.53188436]


### Question 4

Anonymized scores (out of 60) for an examination are stored in a NumPy array.

&nbsp;&nbsp;&nbsp;&nbsp;(a) Write a function that takes the raw scores and returns them as percentages, sorted from lowest to highest. _(Hint: Try using the NumPy sort method.)_ \
&nbsp;&nbsp;&nbsp;&nbsp;(b) Write a function that returns the maximum, minimum and mean raw scores as a dictionary with the keys 'min', 'max' and 'mean'. 

Test your functions using the scores:
`scores = np.array([58.0, 35.0, 24.0, 42, 7.8])`

In [66]:
scores = np.array([58,53,24,42,7.8])

In [65]:
def sort(x):
    x=x/60
    x.sort()
    return x 

In [67]:
percent=sort(scores)
print(percent)

[0.13       0.4        0.7        0.88333333 0.96666667]


In [170]:
def stat(x):
    stats = {"Min":x.min(),"Max":x.max(),'Mean':x.mean()}
    return stats

In [171]:
stat(scores)

{'Min': 7.8, 'Max': 58.0, 'Mean': 36.96}

### Question 5

The position at time t of a ball dropped with zero initial velocity from a height h is given by

$$ y = h - \frac{gt^{2}}{2} $$

where $g = 9.8 m/s^{2}$. Suppose h = 10 m and the ball is dropped at t = 0.\
&nbsp;&nbsp;&nbsp;&nbsp;(a) Find the sequence of times when the ball passes each half meter.<br> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_(Hint: Create a NumPy array ranging from 10 to 0 in -0.5 increments, then solve the above equation for y.)_ \
&nbsp;&nbsp;&nbsp;&nbsp;(b) Find the average velocity (defined as $\frac{Δy}{Δt}$) for each time interval using NumPy arrays.\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_(Hint: Given an array a with 20 elements, what are the arrays `a[1:20]` and `a[0:19]`?)_


In [37]:
import math
time =[]
def position(x):
    for i in x:
        t = math.sqrt(((2*10)-(2*i))/9.8)
        #print("at:{0}m the time is {1}s".format(i,round(t,3)))
        time.append(t)
    return time

In [38]:
e = np.arange(10,-0.5,-0.5)
e

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ])

In [39]:
times = position(e)
times = np.array(times).reshape(21,1)
times

array([[0.        ],
       [0.31943828],
       [0.45175395],
       [0.55328334],
       [0.63887656],
       [0.71428571],
       [0.7824608 ],
       [0.84515425],
       [0.9035079 ],
       [0.95831485],
       [1.01015254],
       [1.05945693],
       [1.10656667],
       [1.15175111],
       [1.19522861],
       [1.23717915],
       [1.27775313],
       [1.31707778],
       [1.35526185],
       [1.39239919],
       [1.42857143]])

In [33]:
delt = times[1:20]-times[0:19]
delt = delt.T

In [68]:
dele = e[0:19]-e[1:20]
dele = dele.T
dele

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [35]:
np.divide(dele[0:20],delt[0:20])

array([[ 1.56524758,  3.77884195,  4.9246827 ,  5.84158351,  6.63049517,
         7.3340579 ,  7.97531375,  8.56844457,  9.12293148,  9.64549022,
        10.14108641, 10.61351563, 11.06575711, 11.50020061, 11.91879801,
        12.32316816, 12.71467146, 13.09446421, 13.46353913]])

### Question 6

(a) Define a function that creates Pandas data frames of the form:

&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;&nbsp;D\
1&nbsp;&nbsp;A1&nbsp;&nbsp;B1&nbsp;&nbsp;C1&nbsp;&nbsp;D1\
2&nbsp;&nbsp;A2&nbsp;&nbsp;B2&nbsp;&nbsp;C2&nbsp;&nbsp;D2

i.e., that simulates the cell names from an Excel spreadsheet.

(b) Use your function to generate two data frames with overlapping, but differing sets of indices and column names. Then test the 4 different combinations of the join and axis parameters of the concat function using these frames.


In [54]:
def dataframe(cols, index):
    data = {column: [str(column)+str(i) for i in index] for column in cols}
    df = pd.DataFrame(data,index=index)
    return df

In [55]:
dataframe('ABCDE',range(1,4))

A   B   C   D   E
1  A1  B1  C1  D1  E1
2  A2  B2  C2  D2  E2
3  A3  B3  C3  D3  E3

In [319]:
b = dataframe('CDEFG',range(3,6))

In [322]:
pd.concat([a,b],axis=0,join='outer')

A    B   C   D   E    F    G
1   A1   B1  C1  D1  E1  NaN  NaN
2   A2   B2  C2  D2  E2  NaN  NaN
3   A3   B3  C3  D3  E3  NaN  NaN
3  NaN  NaN  C3  D3  E3   F3   G3
4  NaN  NaN  C4  D4  E4   F4   G4
5  NaN  NaN  C5  D5  E5   F5   G5

In [324]:
pd.concat([a,b],axis=0,join='inner')

C   D   E
1  C1  D1  E1
2  C2  D2  E2
3  C3  D3  E3
3  C3  D3  E3
4  C4  D4  E4
5  C5  D5  E5

In [326]:
pd.concat([a,b],axis=1,join='outer')

A    B    C    D    E    C    D    E    F    G
1   A1   B1   C1   D1   E1  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   E2  NaN  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3   E3   C3   D3   E3   F3   G3
4  NaN  NaN  NaN  NaN  NaN   C4   D4   E4   F4   G4
5  NaN  NaN  NaN  NaN  NaN   C5   D5   E5   F5   G5

In [327]:
pd.concat([a,b],axis=1,join='inner')

A   B   C   D   E   C   D   E   F   G
3  A3  B3  C3  D3  E3  C3  D3  E3  F3  G3

### Question 7

Download the latest US COVID daily report from https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us, and import it into Python as a data frame, setting the state name as the index. Then perform the following operations:

&nbsp;&nbsp;&nbsp;&nbsp;(a) Remove any empty columns and any rows with more than 20% of the values missing.\
&nbsp;&nbsp;&nbsp;&nbsp;(b) Display the states with the lowest and highest testing and mortality rates. Hint: use sorting\
&nbsp;&nbsp;&nbsp;&nbsp;(c) Print descriptive statistics for confirmed COVID cases, recoveries, and deaths. Hint: use slicing\
&nbsp;&nbsp;&nbsp;&nbsp;(d) Group the states into low and high testing rates (compared to the median), and compute the average mortality rate within each group. Hint: Add a new &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; column storing the grouping variable


In [63]:
import pandas as pd
data = pd.read_csv("D:\Semester_3\Computational Modeling\Assignments\Assignment_4\covid_data.csv")
data

Province_State Country_Region          Last_Update      Lat  \
0                    Alabama             US  2020-10-20 04:30:29  32.3182   
1                     Alaska             US  2020-10-20 04:30:29  61.3707   
2             American Samoa             US  2020-10-20 04:30:29 -14.2710   
3                    Arizona             US  2020-10-20 04:30:29  33.7298   
4                   Arkansas             US  2020-10-20 04:30:29  34.9697   
5                 California             US  2020-10-20 04:30:29  36.1162   
6                   Colorado             US  2020-10-20 04:30:29  39.0598   
7                Connecticut             US  2020-10-20 04:30:29  41.5978   
8                   Delaware             US  2020-10-20 04:30:29  39.3185   
9           Diamond Princess             US  2020-10-20 04:30:29      NaN   
10      District of Columbia             US  2020-10-20 04:30:29  38.8974   
11                   Florida             US  2020-10-20 04:30:29  27.7663   
12                   Georgia             US  2020-10-20 04:30:29  33.0406   
13            Grand Princess             US  2020-10-20 04:30:29      NaN   
14                      Guam             US  2020-10-20 04:30:29  13.4443   
15                    Hawaii             US  2020-10-20 04:30:29  21.0943   
16                     Idaho             US  2020-10-20 04:30:29  44.2405   
17                  Illinois             US  2020-10-20 04:30:29  40.3495   
18                   Indiana             US  2020-10-20 04:30:29  39.8494   
19                      Iowa             US  2020-10-20 04:30:29  42.0115   
20                    Kansas             US  2020-10-20 04:30:29  38.5266   
21                  Kentucky             US  2020-10-20 04:30:29  37.6681   
22                 Louisiana             US  2020-10-20 04:30:29  31.1695   
23                     Maine             US  2020-10-20 04:30:29  44.6939   
24                  Maryland             US  2020-10-20 04:30:29  39.0639   
25             Massachusetts             US  2020-10-20 04:30:29  42.2302   
26                  Michigan             US  2020-10-20 04:30:29  43.3266   
27                 Minnesota             US  2020-10-20 04:30:29  45.6945   
28               Mississippi             US  2020-10-20 04:30:29  32.7416   
29                  Missouri             US  2020-10-20 04:30:29  38.4561   
30                   Montana             US  2020-10-20 04:30:29  46.9219   
31                  Nebraska             US  2020-10-20 04:30:29  41.1254   
32                    Nevada             US  2020-10-20 04:30:29  38.3135   
33             New Hampshire             US  2020-10-20 04:30:29  43.4525   
34                New Jersey             US  2020-10-20 04:30:29  40.2989   
35                New Mexico             US  2020-10-20 04:30:29  34.8405   
36                  New York             US  2020-10-20 04:30:29  42.1657   
37            North Carolina             US  2020-10-20 04:30:29  35.6301   
38              North Dakota             US  2020-10-20 04:30:29  47.5289   
39  Northern Mariana Islands             US  2020-10-20 04:30:29  15.0979   
40                      Ohio             US  2020-10-20 04:30:29  40.3888   
41                  Oklahoma             US  2020-10-20 04:30:29  35.5653   
42                    Oregon             US  2020-10-20 04:30:29  44.5720   
43              Pennsylvania             US  2020-10-20 04:30:29  40.5908   
44               Puerto Rico             US  2020-10-20 04:30:29  18.2208   
45              Rhode Island             US  2020-10-20 04:30:29  41.6809   
46            South Carolina             US  2020-10-20 04:30:29  33.8569   
47              South Dakota             US  2020-10-20 04:30:29  44.2998   
48                 Tennessee             US  2020-10-20 04:30:29  35.7478   
49                     Texas             US  2020-10-20 04:30:29  31.0545   
50                      Utah             US  2020-10-20 04:30:29  40.1500   
51        

In [58]:
data.shape

(58, 18)

In [59]:
data.dropna()

Empty DataFrame
Columns: [Province_State, Country_Region, Last_Update, Lat, Long_, Confirmed, Deaths, Recovered, Active, FIPS, Incident_Rate, People_Tested, People_Hospitalized, Mortality_Rate, UID, ISO3, Testing_Rate, Hospitalization_Rate]
Index: []

In [60]:
for i in data.columns:
    if data[i].isnull().sum() >= (0.20*(data.shape[0])):
        print("column: ",i)
        data.drop(i,axis=1,inplace=True)
    
#data = data.dropna(axis = 0, how = "any", thresh = int(0.2 * a.shape[1]))
#indices = []
#for i in range(data.shape[0]):
#    if (data.iloc[i].isnull().sum()) >= (0.20*data.shape[1]):
#        indices.append(data.index[i])
#        print("row no: ",data.index[i])

#data.drop(indices,axis=0,inplace=True)

#data.reset_index(drop=True,inplace=True)

column:  People_Hospitalized
column:  Hospitalization_Rate


In [61]:
data.shape

(58, 16)

In [64]:
People = data.sort_values(by='Testing_Rate')
#print(People)
print("tested min: ",People.iloc[0]['Province_State'])
print("tested max: ",People.iloc[-1]['Province_State'])

mortality = data.sort_values(by='Mortality_Rate')
print("mortality min: ",mortality.iloc[0]['Province_State'])
print("mortality max: ",mortality.iloc[-1]['Province_State'])

tested min:  American Samoa
tested max:  Grand Princess
mortality min:  Diamond Princess
mortality max:  American Samoa


In [32]:
focus = data.loc[:,'Confirmed':'Recovered']
focus.describe()

Confirmed        Deaths      Recovered
count      56.000000     56.000000      49.000000
mean   146657.660714   3930.642857   66787.816327
std    192078.703010   6010.388886  112637.173388
min         0.000000      0.000000      29.000000
25%     27107.750000    515.250000    7892.000000
50%     97111.500000   1656.000000   25939.000000
75%    173586.500000   4169.250000   92367.000000
max    879645.000000  33366.000000  729762.000000

In [35]:
sort = data.sort_values(by='People_Tested')
median = sort['People_Tested'].median()
#print(median)
data.reset_index()
for i in range(len(data)):
    if data.at[i,'People_Tested'] > median:
        data.at[i,'group'] = 'high'
    else:
        data.at[i,'group'] = 'low'

1242007.0


In [48]:
group = data.groupby(['group'])
high = group.get_group('high').mean()['Mortality_Rate']
low = group.get_group('low').mean()['Mortality_Rate']

print("Mortality Rate for High testing: ",high)
print("Mortality Rate for low testing: ",low)

Mortality Rate for High testing:  2.957637523197492
Mortality Rate for low testing:  1.908990590310143


### Question 8

Write a script that computes the Euclidean distance between two points stored as Pandas series in the following format:
<pre><code><strong>
x    25.50
y     3.20
z    -0.24
Name: v, dtype: float64
</pre></code></strong>

i.e., with the index attribute storing the coordinate names. Include checks that the two points have the same dimensionality and the same coordinate names. Ensure coordinates are aligned before computing the distance.\
Test your code using the following two points:\
`p = pd.Series({'x':25.5, 'y':3.2, 'z':-0.24})`\
`q = pd.Series({'z':7.3, 'x':-4.62, 'y':-1.4})`\
The result should be:\
31.38830992583067


In [42]:
p = pd.Series({"x":25.5,"y":3.2,"z":-0.24})
q = pd.Series({"z":7.3,"x":-4.62,"y":-1.4})

In [38]:
def euclindean(p,q):
    euclideandist = 0
    if p.size == q.size:
        for a in p.index:
            for b in q.index:
                if a==b:
                    euclideandist +=((q[b]-p[a])**2)
        euclideandist = math.sqrt(euclideandist)
        print(euclideandist)
    else:
        print("Dimensions dont match")

In [43]:
euclindean(p,q)

31.38830992583067
